# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-20 09:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('lonely_planet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('ride_from', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_location', to='lonely_planet.Location')),
                ('ride_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_location', to='lonely_planet.Location')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
