# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-02-21 20:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_reservation_reservatin_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='reservatin_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 2, 21, 20, 1, 58, 75686)),
        ),
    ]
