# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-20 09:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=200)),
                ('city_description', models.CharField(default='', max_length=250)),
                ('city_image', models.ImageField(blank=True, upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=200)),
                ('country_description', models.CharField(default='', max_length=250)),
                ('country_image', models.ImageField(blank=True, upload_to='static/')),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hotel_name', models.CharField(max_length=250)),
                ('hotel_image', models.ImageField(blank=True, upload_to='static/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lonely_planet.City')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('location_description', models.TextField(default='')),
                ('location_image', models.ImageField(blank=True, upload_to='static/')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lonely_planet.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lonely_planet.Country'),
        ),
    ]
