# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-21 16:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lonely_planet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_rate',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(195)]),
        ),
        migrations.AddField(
            model_name='country',
            name='country_rate',
            field=models.IntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(195)]),
        ),
    ]
